name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build --release
          cargo test
          ./target/release/e2e
          ./target/release/ty obj test/main.ty
          ./target/release/ty link test/main -o .ty-cache/main.o

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build --release
          cargo test
          ./target/release/e2e
          ./target/release/ty obj test/main.ty
          ./target/release/ty link test/main -o .ty-cache/main.o

  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build --release
          cargo test
          ./target/release/e2e
          ./target/release/ty obj test/main.ty
          ./target/release/ty link test/main -o .ty-cache/main.o
