name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    strategy:
      matrix:
        # TODO:: add back windows-latest
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          zig fmt ./src --check
          zig fmt build.zig --check
  test-release:
    strategy:
      matrix:
        # TODO:: add back windows-latest
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: coffeebe4code/craneliftc
      - uses: dtolnay/rust-toolchain@stable
        with:
          path: ../craneliftc
          toolchain: nightly
      - run: |
          make release
      - uses: goto-bus-stop/setup-zig@v2
          path: ../type-lang
      - run: |
          zig build -Doptimize=ReleaseSafe
          zig build test -Doptimize=ReleaseSafe
  test-debug:
    strategy:
      matrix:
        # TODO:: add back windows-latest
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: coffeebe4code/craneliftc
      - uses: dtolnay/rust-toolchain@stable
        with:
          path: ../craneliftc
          toolchain: nightly
      # TODO:: make debug when build supports debug
      - run: |
          make release
      - uses: goto-bus-stop/setup-zig@v2
          path: ../type-lang
      - run: |
          zig build
          zig build test
