name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build --release
          if ($LASTEXITCODE) { throw "Error" }
          cargo test
          if ($LASTEXITCODE) { throw "Error" }
          ./target/release/e2e
          if ($LASTEXITCODE) { throw "Error" }
          ./target/release/ty obj test/main.ty
          if ($LASTEXITCODE) { throw "Error" }
          ./target/release/ty link main -o .ty/main.o
          if ($LASTEXITCODE) { throw "Error" }
          ./target/main
          if ($LASTEXITCODE) { throw "Error" }
        shell: pwsh

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build --release
          cargo test
          ./target/release/e2e
          ./target/release/ty obj test/main.ty
          ./target/release/ty link main -o .ty/main.o
          ./target/main

  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build --release
          cargo test
          ./target/release/e2e
          ./target/release/ty obj test/main.ty
          ./target/release/ty link main -o .ty/main.o
          ./target/main
